DROP TRIGGER IF EXISTS MOVE_BEFORE_INSERT;
CREATE TRIGGER MOVE_BEFORE_INSERT BEFORE INSERT ON MOVE 
FOR EACH ROW
SET NEW.MOVE_NUM=(SELECT COUNT(*) FROM MOVE WHERE TURN_UUID=NEW.TURN_UUID);
DROP TRIGGER IF EXISTS TURN_BEFORE_INSERT;
CREATE TRIGGER TURN_BEFORE_INSERT BEFORE INSERT ON TURN 
FOR EACH ROW
SET NEW.TURN_NUM=(SELECT COUNT(*) FROM MOVE WHERE GAME_UUID=NEW.GAME_UUID);